name: "Feature Request"
description: "Suggest a new feature or request to remove an existing one"
title: "[Feature Request]: <Brief Description>"
labels: ["enhancement", "feature request"]

body:
  - type: markdown
    attributes:
      value: |
        ## 🚀 Feature Request
        Thank you for taking the time to propose a feature! Please provide as much detail as possible.
  
  - type: textarea
    id: feature_description
    attributes:
      label: "Describe the Feature"
      description: "Provide a clear and concise description of the feature you want to add or remove."
      placeholder: "What is the feature about? Why is it needed?"
    validations:
      required: true

  - type: dropdown
    id: feature_type
    attributes:
      label: "Feature Type"
      description: "Select whether this is a new feature or a request to remove an existing one."
      options:
        - "New Feature"
        - "Remove Existing Feature"
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: "Motivation & Use Case"
      description: "Explain why this feature should be added or removed. What problem does it solve?"
      placeholder: "Describe how this feature will benefit the users."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives Considered"
      description: "Have you considered any alternatives or workarounds?"
      placeholder: "Mention any other solutions you have thought about."
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Add any other relevant context or screenshots about the request."
      placeholder: "You can also link related issues here."
    validations:
      required: false
