name: "Bug Report"
description: "Report a bug or issue with the project."
labels: ["bug"]
body:
  - type: textarea
    id: describe
    attributes:
      label: "Bug Description"
      description: "Describe the bug in detail. Include steps to reproduce, expected behavior, and actual behavior."
      placeholder: "Provide a clear and concise description of what the bug is."
    validations:
      required: true